<?php

$square = $this->square;
$squareType = $this->option('subject.square.type');

$dateStart = $this->dateStart;
$dateEnd = $this->dateEnd;

$this->setup(array(
    'title' => sprintf('%s-%s', $squareType, $this->t('Booking')),
    'panel' => 'centered-panel',
    'messages' => array(
        'error' => $this->message,
    ),
    'back' => true,
));

?>

<script type="text/javascript">
function showHide() {
   var div = document.getElementById('hidden_div');
   if (div.style.display == 'none') {
     div.style = 'position:absolute; top:0; right:0; bottom:0; left:0; background-color: gray; opacity: .5;';
   }
   else {
     div.style.display = 'none';
   }
}
</script>


<div class="padded">

    <form id="confirmform" method="post" onSubmit="showHide();" action="<?= $this->url ?>">
<?php

        $pricingSummary = $this->squarePricingSummary($dateStart, $dateEnd, $square, $this->quantityChoosen, $this->products);

        if ($pricingSummary) {
            echo '<p class="centered-text gray"><em>' . $this->t('Summary of your booking:') . '</em></p>';
            echo '<div class="sandbox">' . $pricingSummary . '</div>';
            echo '<div class="separator separator-line"></div>';
        }

?>

        <?php if ($this->hasBudget): ?>
        <p class="symbolic symbolic-warning"><b><?= $this->t('payment from open budget') ?>:</b></p>
        <div style="margin-left: 22px;margin-bottom: 22px;"><b>Budget: <?= $this->budget ?> -> <?= $this->t('new budget') ?> : <?= $this->newbudget ?></b></div>   
        <?php endif; ?>

        <?php if ($square->getMeta('rules.document.file')): ?>

            <p class="symbolic symbolic-warning"><b><?= $this->t('Please note') ?>:</b></p>

            <p style="margin-left: 32px;">
                <!-- <a href="<?= $this->basePath($square->getMeta('rules.document.file')) ?>" class="default-button" target="_blank"> -->
                <a href="<?= $this->basePath('../extern/hallenordnung11.pdf') ?>" class="default-button" target="_blank">
                    <span class="symbolic symbolic-attachment"><?= $square->getMeta('rules.document.name', $this->t('Rules-document')) ?></span>
                </a>

                <span class="small-text gray">(<?= $this->t('this will open in a new window') ?>)</span>
            </p>

            <div style="margin-left: 32px;">
                <input type="checkbox" name="bf-accept-rules-document" id="bf-accept-rules-document">
                <label for="bf-accept-rules-document"><?= sprintf($this->t('Yes, I have %1$sread and accepted%2$s the "%3$s"'), '<b>', '</b>', $square->getMeta('rules.document.name', $this->t('Rules-document'))) ?></label>
            </div>

            <div class="separator separator-line"></div>

        <?php endif; ?>

        <?php if ($square->getMeta('rules.text')): ?>

            <p class="symbolic symbolic-warning"><b><?= $this->t('Please note') ?>:</b></p>

            <div style="margin-left: 32px;"><?= $square->getMeta('rules.text') ?></div>

            <div style="margin-left: 32px;">
                <input type="checkbox" name="bf-accept-rules-text" id="bf-accept-rules-text">
                <label for="bf-accept-rules-text"><?= sprintf($this->t('Yes, I have %sread and accepted%s these rules and notes'), '<b>', '</b>') ?></label>
            </div>

            <div class="separator separator-line"></div>

        <?php endif; ?>
        
        <?php if ($square->get('allow_notes')): ?>

            <textarea name="bf-user-notes" placeholder="Optionale Anmerkungen" style="width: 95%; height: 3.1rem"></textarea>

            <div class="separator separator-line"></div>

        <?php endif; ?>

        <!-- <div class="centered-text">
            <form action="<?= $this->url('booking', 'addToCart') ?>" method="post">
                <input type="hidden" name="bf-confirm" value="<?= sha1('Quick and dirty' . floor(time() / 1800)) ?>">
                <input type="hidden" name="squareId" value="<?= $square->getId() ?>">
                <button type="submit" name="bf-submit" id="bf-submit" class="default-button">
                    <?= $this->t('Add to Cart') ?>
                </button>
            </form>
        </div> -->


    </form>

</div>

<div id="hidden_div" style="display:none" >
</div>
