<?php
$square = $this->square;
$squareType = $this->option('subject.square.type');

$dateStart = $this->dateStart;
$dateEnd = $this->dateEnd;

$this->setup(array(
    'title' => sprintf('%s-%s', $squareType, $this->t('Booking')),
    'panel' => 'centered-panel',
    'messages' => array(
        'error' => $this->message,
    ),
    'back' => true,
));
?>

<script type="text/javascript">
function showHide() {
   var div = document.getElementById('hidden_div');
   if (div.style.display == 'none') {
     div.style = 'position:absolute; top:0; right:0; bottom:0; left:0; background-color: gray; opacity: .5;';
   }
   else {
     div.style.display = 'none';
   }
}
</script>

<div class="padded">
    <form id="confirmform" method="post" onSubmit="showHide();" action="<?= $this->url ?>">
        <?php
        $pricingSummary = $this->squarePricingSummary($dateStart, $dateEnd, $square, $this->quantityChoosen, $this->products);

        if ($pricingSummary) {
            echo '<p class="centered-text gray"><em>' . $this->t('Summary of your booking:') . '</em></p>';
            echo '<div class="sandbox">' . $pricingSummary . '</div>';
            echo '<div class="separator separator-line"></div>';
        }

        if ($this->hasBudget) {
            echo '<p class="symbolic symbolic-warning"><b>' . $this->t('payment from open budget') . ':</b></p>';
            echo '<div style="margin-left: 22px;margin-bottom: 22px;"><b>Budget: ' . $this->budget . ' -> ' . $this->t('new budget') . ': ' . $this->newbudget . '</b></div>';
        }

        if ($square->getMeta('rules.document.file')) {
            echo '<p class="symbolic symbolic-warning"><b>' . $this->t('Please note') . ':</b></p>';
            echo '<p style="margin-left: 32px;">';
            echo '<a href="' . $this->basePath($square->getMeta('rules.document.file')) . '" class="default-button" target="_blank">';
            echo '<span class="symbolic symbolic-attachment">' . $square->getMeta('rules.document.name', $this->t('Rules-document')) . '</span>';
            echo '</a>';
            echo '<span class="small-text gray">(' . $this->t('this will open in a new window') . ')</span>';
            echo '</p>';
            echo '<div style="margin-left: 32px;">';
            echo '<input type="checkbox" name="bf-accept-rules-document" id="bf-accept-rules-document">';
            echo '<label for="bf-accept-rules-document">' . sprintf($this->t('Yes, I have %1$sread and accepted%2$s the "%3$s"'), '<b>', '</b>', $square->getMeta('rules.document.name', $this->t('Rules-document'))) . '</label>';
            echo '</div>';
            echo '<div class="separator separator
