<?php

$this->setup(array(
    'title' => 'My bookings',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'My account' => $this->url('user/settings'),
    ),
));

?>

<div>
    <h1><?= $this->translate('Booking Cart') ?></h1>

    <div class="separator-small"></div>

    <?php if (count($this->cartItems) == 0): ?>
        <p><?= sprintf($this->translate('Your cart is empty.')) ?></p>
    <?php elseif (count($this->cartItems) == 1): ?>
        <p><?= sprintf($this->translate('You have one item in your cart.')) ?></p>
    <?php else: ?>
        <p><?= sprintf($this->translate('You have %s items in your cart.'), count($this->cartItems)) ?></p>
    <?php endif; ?>

    <?php if (count($this->cartItems) > 0): ?>

        <div class="separator separator-line"></div>

        <style type="text/css">
            .default-table td { padding-right: 16px; padding-bottom: 8px; height: 24px; }
        </style>

        <table class="default-table middle-table">
            <?php foreach ($this->cartItems as $cartItem): ?>
                <tr>
                    <td><?= $cartItem['name'] ?></td>
                    <td><?= $cartItem['price'] ?></td>
                </tr>
            <?php endforeach; ?>
        </table>

        <div class="separator-small"></div>

    <?php endif; ?>

</div>
